version: '3.8'

services:
  postgres:
    container_name: e-commerce-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: e-commerce
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: e-commerce-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
